kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: shocki/alpine-devpi-client
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
