kind: pipeline
name: build-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: shocki/alpine-devpi-client
    auto_tag: true
    auto_tag_suffix: linux-amd64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
---
kind: pipeline
name: build-arm

platform:
  os: linux
  arch: arm

steps:
- name: docker  
  image: plugins/docker:linux-arm
  settings:
    repo: shocki/alpine-devpi-client
    auto_tag: true
    auto_tag_suffix: linux-arm
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

---
kind: pipeline
name: publish-manifest

steps:
- name: manifest
  image: plugins/manifest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    target: shocki/alpine-devpi-client:latest
    template: shocki/alpine-devpi-client:latest-OS-ARCH
    platforms:
      - linux/amd64
      - linux/arm

trigger:
  status:
    - success

depends_on:
  - build-arm
  - build-amd64

